---
title: "<br><br>Swissvotes Database<br><br>"
output: 
  html_document:
    toc: yes
    code_folding: show
editor_options: 
  chunk_output_type: console
---

\
\

## Setup

```{r message=FALSE, warning=FALSE}
# packages/functions
library(tidyverse)
library(tidytext)
library(tidymodels)
library(vip)
library(glue)
library(scales)
theme_set(theme_minimal())

`%ni%` <- negate(`%in%`)

# data
df_raw <- readxl::read_xlsx(here::here("01_data",
                                       "DATASET XLSX 31-01-2024.xlsx"),
                            sheet = "DATA") %>% 
  janitor::clean_names()
```

\
\

## Data processing

```{r message=FALSE, warning=FALSE}
# df_raw %>% 
#   glimpse()

# df_raw %>% 
#   View()


### 1) Define NAs
df <- df_raw %>% 
  mutate(across(where(is.character), ~na_if(., ".")),
         across(where(is.character), ~na_if(., "")),
         across(where(is.character), ~na_if(., " ")))


### 2) parse dates (NOTE: 2 different formats...)
date_1 <- df %>%
  slice(1:55) %>% 
  select(anr, datum) %>% 
  mutate(datum = dmy(datum))

date_2 <- df %>% 
  slice(56:nrow(.)) %>% 
  select(anr, datum) %>% 
  mutate(datum = as.numeric(datum),
         datum = as.Date(datum,
                         origin = "1899-12-30"))

new_dates <- date_1 %>% 
  bind_rows(date_2) %>% 
  arrange(anr)

# check
# summary(new_dates)

# recreate df
df <- df %>% 
  arrange(anr) %>% 
  mutate(datum = new_dates$datum)


### 3) create decade
df <- df %>%  
  mutate(decade =  floor_date(datum, 
                              unit = "10 years"))


### 4) create factors
df <- df %>% 
  mutate(
    rechtsform = factor(
      x = rechtsform,
      labels = c("Obligatorisches Referendum",
                 "Falkultatives Referendum",
                 "Volksinitiative",
                 "Direkter Gegenentwurf",
                 "Stichfrage")),
    d1e1 = factor(
      x = d1e1,
      labels = c("Staatsordnung",
                 "Aussenpolitik",
                 "Sicherheitspolitik",
                 "Wirtschaft",
                 "Landwirtschaft",
                 "Öffentliche Finanzen",
                 "Energie",
                 "Verkehr und Infrastruktur",
                 "Umwelt und Lebensraum",
                 "Sozialpolitik",
                 "Bildung und Forschung",
                 "Kultur, Religion, Medien")),
    dep = factor(
      x = dep,
      labels = c("EDA",
                 "EDI",
                 "EJDP",
                 "VBS",
                 "EFD",
                 "WBF",
                 "UVEK",
                 "BK"))
  ) %>% 
  mutate(
    across(c(br_pos, sr_pos, nr_pos), ~factor(x = .,
                                              labels = c("Befürwortend", 
                                                         "Ablehnend",
                                                         "keine",
                                                         "Vorzug Gegenentwurf")))
  ) %>% 
  mutate(
    across(c(p_svp, p_sps, p_fdp, p_mitte), ~ case_when(
      . == "1" ~ 1,
      . == "2" ~ 2,
      TRUE ~ 3
    ))
  ) %>% 
  mutate(
    across(c(p_svp, p_sps, p_fdp, p_mitte), ~factor(x = .,
                                                    labels = c("Ja-Parole",
                                                               "Nein-Parole",
                                                               "Keine Parole")))
  )

### 5) numeric variables
df <- df %>% 
  mutate(annahme = parse_number(annahme),
         br_ja = br_pos == "Befürwortend",
         sr_ja = sr_pos == "Befürwortend",
         nr_ja = nr_pos == "Befürwortend",
         bet = parse_number(bet))
```

\
\

## EDA

### Over time

```{r message=FALSE, warning=FALSE, fig.width=12, fig.height=8}
### 1)
df %>% 
  count(decade, rechtsform) %>% 
  mutate(rechtsform = fct_reorder(rechtsform,
                                  n,
                                  .fun = max)) %>% 
  ggplot(aes(decade, n)) + 
  geom_line(aes(color = rechtsform,
                group = rechtsform),
            linewidth = 1) + 
  labs(title = "\nAnzahl Abstimmungen über Zeit nach Rechtsform",
       subtitle = "Aggregationsstufe: 10 Jahre\n",
       x = "\nJahr",
       y = "Anzahl\n",
       color = "Rechtsform") + 
  scale_color_discrete(guide = guide_legend(reverse = TRUE))


### 2)
df %>% 
  filter(!is.na(bet)) %>% 
  ggplot(aes(datum, bet)) + 
  geom_line(group = 1) +
  geom_smooth() +
  labs(title = "\nStimmbeteiligung über Zeit\n",
       x = "\nJahr",
       y = "Stimmbeteiligung\n") + 
  scale_y_continuous(labels = percent_format(scale = 1))


### 3)
df %>% 
  filter(!is.na(annahme)) %>% 
  mutate(annahme = ifelse(annahme == 1, "Ja", "Nein")) %>% 
  count(annahme) %>% 
  ggplot(aes(annahme, n)) + 
  geom_col(aes(fill = annahme),
           show.legend = FALSE) + 
  geom_label(aes(label = glue("{n}"))) +
  labs(title = "\nAnzahl angenommene vs. abgelehnte Initiativen\n",
       x = "\nAngenommen?",
       y = "")


### 4)
df %>% 
  filter(!is.na(annahme)) %>% 
  mutate(annahme = ifelse(annahme == 1, "Ja", "Nein")) %>% 
  count(rechtsform, annahme) %>% 
  mutate(rechtsform = fct_reorder(rechtsform, 
                                  n)) %>% 
  ggplot(aes(annahme, n)) + 
  geom_col(aes(fill = rechtsform),
           position = "dodge2") + 
  geom_label(aes(label = glue("{n}"),
                 group = rechtsform),
             position = position_dodge(width = .9)) + 
  labs(title = "\nAnzahl angenommene vs. abgelehnte Initiativen nach Rechtsform\n",
       x = "\nAngenommen?",
       y = "",
       fill = "Rechtsform")


### 5) 
df %>% 
  filter(!is.na(annahme)) %>% 
  mutate(annahme = ifelse(annahme == 1, "Ja", "Nein")) %>% 
  group_by(rechtsform) %>% 
  summarise(n_angenommen = sum(annahme == "Ja"),
            n_abgelehnt = sum(annahme == "Nein"),
            n_tot = n_angenommen + n_abgelehnt,
            pct_angenommen = n_angenommen / n_tot) %>% 
  mutate(rechtsform = fct_reorder(rechtsform, 
                                  pct_angenommen)) %>% 
  ggplot(aes(pct_angenommen, rechtsform)) + 
  geom_col(aes(fill = rechtsform),
           position = "dodge") +
  geom_label(aes(label = glue("{round(100 * pct_angenommen, 2)}%"))) + 
  scale_x_continuous(breaks = seq(0, 1, 0.2),
                     labels = scales::percent_format()) + 
  expand_limits(x = c(0, 1)) +
  labs(title = "\nProzentualer Anteil angenommener Initiativen nach Rechtsform\n",
       x = "",
       y = "",
       fill = "Rechtsform")

### 6)
df_plot <- df %>% 
  mutate(annahme = ifelse(annahme == 1, "Ja", "Nein")) %>% 
  filter(!is.na(annahme)) %>% 
  group_by(rechtsform, d1e1) %>% 
  summarise(n_angenommen = sum(annahme == "Ja"),
            n_abgelehnt = sum(annahme == "Nein"),
            n_tot = n_angenommen + n_abgelehnt,
            pct_angenommen = n_angenommen / n_tot) %>%
  mutate(d1e1 = glue("{d1e1} ({n_tot})"))

rechtsformen <- df_plot %>% 
  pull(rechtsform) %>% 
  unique()

for(i in rechtsformen) {
  
  print(
    
    df_plot %>% 
      filter(rechtsform == i) %>% 
      mutate(d1e1 = fct_reorder(d1e1, pct_angenommen)) %>% 
      ggplot(aes(pct_angenommen, d1e1)) + 
      geom_col(aes(fill = d1e1),
               position = "dodge",
               show.legend = FALSE) +
      geom_label(aes(label = glue("{round(100 * pct_angenommen, 2)}%"))) + 
      scale_x_continuous(breaks = seq(0, 1, 0.2),
                         labels = scales::percent_format()) + 
      expand_limits(x = c(0, 1)) +
      labs(title = glue("\nProzent Angenommen - {i}"),
           subtitle = "Totale Anzahl Beobachtungen in (...)\n",
           x = "",
           y = "") 
    
  )
  
}
```


### Words/descriptions

```{r message=FALSE, warning=FALSE}
### 1. create df_words
df_words <- df %>% 
  select(anr, kurzbetitel) %>% 
  unnest_tokens("word",
                kurzbetitel)

### 2. remove stop words
stop_words_DE <- tibble(
  word = c(stopwords::stopwords("de"),
           "ja", "nein", "initiative",
           "mehr", "bleibt", "bleiben",
           "beim", "weiterhin", "zweiten",
           "erhält", "erste", "klares",
           "knapp", "ab", "bringt",
           "nimmt", "dritten", "erneut")
)

df_words_processed <- df_words %>% 
  anti_join(stop_words_DE,
            by = "word") %>% 
  filter(!is.na(word)) %>% 
  mutate(word = case_when(
    word == "verhindert" ~ "verhindern",
    word == "bundes" ~ "bund",
    TRUE ~ word
  ))


### 3. create sparse matrix
df_words_matrix <- df_words_processed %>% 
  add_count(word,
            name = "n_word") %>% 
  filter(n_word > 10) %>% 
  distinct(anr, word) %>% 
  mutate(word_value = 1) %>% 
  pivot_wider(
    names_from = word,
    values_from = word_value,
    values_fill = list(word_value = 0)
  )


### 4. Create data set for modelling
df_model <- df_words_matrix %>% 
  inner_join(df %>% 
               select(anr, datum, annahme, volkja_proz,
                      rechtsform, d1e1,
                      br_ja, sr_ja, nr_ja,
                      p_svp, p_sps, p_fdp, p_mitte,
                      bet),
             by = "anr")

df_model %>% 
  skimr::skim()
```

\
\

## Lasso-regression

```{r message=FALSE, warning=FALSE}
### 1) Testing and training set
set.seed(1234)
split <- initial_split(df_model %>% 
                         filter(!is.na(annahme)), 
                       strata = annahme)
train <- training(split)
test <- testing(split)


### 2) Recipe
rec <- recipe(volkja_proz ~ .,
              data = train) %>% 
  update_role(anr, annahme, datum, 
              new_role = "ID") %>%
  step_dummy(rechtsform, d1e1,
             p_svp, p_sps, p_fdp, p_mitte) %>% 
  step_mutate(br_ja = as.numeric(br_ja),
              sr_ja = as.numeric(sr_ja),
              nr_ja = as.numeric(nr_ja)) %>%
  step_impute_mean(all_predictors()) %>% 
  step_zv(all_predictors()) %>%
  step_normalize(all_predictors())

rec %>%
  prep() %>%
  juice() %>% 
  glimpse()



### 3) Specify model
lasso_spec <- linear_reg(mode = "regression",
                         penalty = 0.1,
                         mixture = 1) %>% 
  set_engine("glmnet")

wf <- workflow() %>% 
  add_recipe(rec)


### 4) Fit model
lasso_fit <- wf %>% 
  add_model(lasso_spec) %>% 
  fit(data = train)

# lasso_fit %>% 
#   extract_fit_parsnip() %>% 
#   tidy()
```


### Tune lasso parameters

```{r message=FALSE, warning=FALSE, fig.width=12, fig.height=8}
### 1) Setup
set.seed(1234)
df_boot <- bootstraps(train, 
                      strata = annahme)

tune_spec <- linear_reg(penalty = tune(), 
                        mixture = 1) %>%
  set_engine("glmnet")

lambda_grid <- grid_regular(penalty(), 
                            levels = 200)


### 2) Fit resamples
set.seed(1234)
lasso_grid <- tune_grid(wf %>% 
                          add_model(tune_spec),
                        resamples = df_boot,  
                        grid = lambda_grid)

lasso_grid %>% 
  collect_metrics() %>% 
  ggplot(aes(penalty, mean, 
             color = .metric)) + 
  geom_errorbar(aes(ymin = mean - std_err,
                    ymax = mean + std_err),
                alpha = 0.5) + 
  geom_line(linewidth = 1.5) + 
  facet_wrap(~ .metric,
             scales = "free",
             nrow = 2)
```

### Select best

```{r message=FALSE, warning=FALSE, fig.width=12, fig.height=8}
### 3) Select best model
lowest_rmse <- lasso_grid %>%
  select_best("rmse")

final_lasso <- finalize_workflow(wf %>% 
                                   add_model(tune_spec),
                                 lowest_rmse)


### 3) Visualize results
final_lasso %>%
  fit(train) %>%
  pull_workflow_fit() %>%
  vi(lambda = lowest_rmse$penalty) %>%
  mutate(Importance = abs(Importance),
         Variable = fct_reorder(Variable, Importance)) %>% 
  filter(Importance > 0) %>% 
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) +
  geom_col() +
  scale_x_continuous(expand = c(0, 0)) +
  labs(y = "")


last_fit(
  final_lasso,
  split
) %>%
  collect_metrics()
```

\
\
